"""Build the frozen v1 validation corpus (tests/v1_validation/).

Every prompt here is new for v1: none was used in RC4 or in v1 development, and
none was selected by running it through Sabah. Two prompts per category.

Outputs
  prompts.jsonl   chat prompts (diag manifest format)
  ubatch.jsonl    exact-length token prompts for the ubatch-boundary gate
  manifest.json   ids, categories, roles, SHA-256 of prompt bytes / token ids

Token prompts are produced by the pinned tokenizer through
`llama-sabah-diag` with SABAH_DIAG_TOKENIZE_ONLY=1, from a passage generated by
a seeded template, then truncated to the preregistered lengths.
"""
from __future__ import annotations

import hashlib
import json
import os
import random
import subprocess
import sys

import numpy as np

HERE = os.path.dirname(os.path.abspath(__file__))
V5 = os.path.abspath(os.path.join(HERE, "..", ".."))
OUT = os.path.join(V5, "tests", "v1_validation")
sys.path.insert(0, HERE)
from run_path import DIAG, MODEL  # noqa: E402

LONG_1 = (
    "The Varna Salt Cooperative was founded in 1911 by eleven families who worked the shallow lagoons south "
    "of the harbour. For the first decade they sold coarse grey salt to fish-curers along the coast, carrying "
    "it in flat-bottomed boats that could cross the lagoon at low water. In 1924 a storm breached the outer "
    "dyke and flooded half of the evaporation pans with fresh water; three seasons of production were lost, "
    "and six of the founding families left for the city. The remaining members borrowed money from a grain "
    "merchant, rebuilt the dyke with stone instead of packed clay, and switched from grey salt to a finer white "
    "salt that could be sold to bakeries. By 1935 the cooperative employed forty workers during the summer "
    "harvest and had bought a small steam pump. The pump allowed them to move brine between pans in a fixed "
    "sequence, which raised the yield per hectare by roughly a third. During the war the harbour was closed "
    "and the salt was moved inland by cart. After 1950 the cooperative slowly declined: refrigeration reduced "
    "demand from fish-curers, and a large industrial plant opened eighty kilometres to the north. The last "
    "harvest took place in 1971. Today the pans are a bird reserve, and the old pump house is a small museum.")
LONG_2 = (
    "Mira kept a notebook of every bridge she crossed during a month of walking along the river. On the first "
    "day she counted a rope footbridge near the source, swaying above a narrow gorge. Two days later she "
    "reached a stone arch with seven spans, built, according to a plaque, by monks who charged a toll in "
    "candles. In the market town she crossed an iron bridge painted green, then a concrete road bridge that "
    "carried lorries toward the motorway. Further down the valley the river widened and the bridges became "
    "rarer; for four days she saw only a ferry, a wooden raft pulled along a cable by an old man who refused "
    "payment and asked instead for news from upstream. Near the estuary she found a railway viaduct, so tall "
    "that swallows nested under its deck, and finally a swing bridge that opened twice a day to let fishing "
    "boats reach the sea. On the last page of the notebook she wrote that the bridges had told her the "
    "history of the valley better than any book: who travelled, what they carried, and who paid for the crossing.")

PROMPTS = [
    ("english_prose_1", "english_prose", "Describe, in about five sentences, how a lighthouse keeper in the 1890s might have spent a stormy winter night."),
    ("english_prose_2", "english_prose", "Write a short paragraph explaining to a curious ten-year-old why bread goes stale."),
    ("turkish_prose_1", "turkish_prose", "Kapadokya'daki peri bacalarının nasıl oluştuğunu beş cümleyle anlat."),
    ("turkish_prose_2", "turkish_prose", "Bir köy kahvesinde geçen kısa ve sıcak bir sabah sahnesi yaz."),
    ("python_code_1", "python_code", "Write a Python function that merges overlapping intervals given as a list of (start, end) tuples. Include a docstring and two example calls."),
    ("python_code_2", "python_code", "Explain what this Python code prints and why:\n\nx = [[0] * 3] * 3\nx[0][1] = 7\nprint(x)"),
    ("json_1", "structured_json", "Return only a JSON object describing a fictional bookstore with the fields name, city, founded_year, and books: a list of three books, each with title, author and price."),
    ("json_2", "structured_json", "Convert this into JSON with keys \"station\" and \"readings\" (a list of objects with \"hour\" and \"celsius\"): Station Kuzey recorded 4.5 degrees at 06:00, 7.0 at 09:00 and 11.25 at 12:00."),
    ("math_1", "math_reasoning", "A train leaves at 14:35 and travels 312 km at an average speed of 96 km/h. At what time does it arrive? Show your reasoning."),
    ("math_2", "math_reasoning", "What is the sum of all positive integers below 200 that are divisible by 3 or by 7? Explain step by step."),
    ("instruction_1", "instruction_following", "List exactly four uses of copper, one per line. Each line must start with a dash and contain at most six words."),
    ("instruction_2", "instruction_following", "Rewrite the sentence 'The committee has decided to postpone the meeting until further notice' in three tones: formal, casual and humorous. Label each version."),
    ("long_context_1", "long_context", LONG_1 + "\n\nBased only on the text above: why did the cooperative switch from grey salt to white salt, and what made that possible?"),
    ("long_context_2", "long_context", LONG_2 + "\n\nSummarise the text above in three sentences, and name the bridge Mira found most unusual."),
]

# preregistered roles (see docs/V1_CORRECTNESS_CONTRACT.md)
ROLES = {
    "sentinel": ["english_prose_1", "turkish_prose_1", "python_code_1", "math_1"],
    "cache_invariance": ["json_1", "instruction_1"],
    "determinism_repeat": ["json_1", "math_1"],
    "multiseq": ["english_prose_2", "turkish_prose_2", "python_code_2", "json_2"],
    "api_ab": ["math_2", "instruction_2", "long_context_1", "english_prose_1"],
    "api_concurrency_1": ["math_2"],
    "api_concurrency_2": ["instruction_2", "turkish_prose_2"],
    "api_concurrency_4": ["english_prose_1", "python_code_1", "json_1", "long_context_2"],
    "api_stream": ["math_1"],
    "benchmark": ["math_1"],
}
UBATCH_LENGTHS = [511, 512, 513, 1100]
UBATCH_SEED = 20260919


def ubatch_passage(seed=UBATCH_SEED, n_sentences=260):
    rng = random.Random(seed)
    towns = ["Arlen", "Belcourt", "Corvid", "Dunmore", "Esker", "Falk", "Garrow", "Hollin", "Istra", "Jessup"]
    trades = ["weavers", "coopers", "tanners", "glassblowers", "millers", "ropemakers", "potters", "smiths"]
    goods = ["wool", "barrels", "leather", "lamps", "flour", "rope", "jugs", "nails", "salt", "honey"]
    out = []
    for i in range(n_sentences):
        out.append("In year %d the %s of %s sent %d loads of %s to %s, and the river was %s." % (
            1700 + rng.randrange(250), rng.choice(trades), rng.choice(towns), rng.randrange(2, 90),
            rng.choice(goods), rng.choice(towns), rng.choice(["high", "low", "frozen", "calm", "fast"])))
    return " ".join(out)


def sha(b):
    return hashlib.sha256(b).hexdigest()


def main():
    os.makedirs(OUT, exist_ok=True)
    with open(os.path.join(OUT, "prompts.jsonl"), "w", encoding="utf-8", newline="\n") as f:
        for pid, cat, text in PROMPTS:
            f.write(json.dumps({"id": pid, "text": text}, ensure_ascii=False) + "\n")

    # tokenize the passage with the pinned tokenizer (raw text, as run)
    tmp = os.path.join(OUT, "_tok")
    os.makedirs(tmp, exist_ok=True)
    passage = ubatch_passage()
    mf = os.path.join(tmp, "passage.jsonl")
    open(mf, "w", encoding="utf-8").write(json.dumps({"id": "passage", "text": passage, "raw": True}) + "\n")
    env = dict(os.environ, SABAH_DIAG_OUT=tmp, SABAH_DIAG_MANIFEST=mf, SABAH_DIAG_TOKENIZE_ONLY="1")
    subprocess.run([DIAG, "-m", MODEL, "-c", "4096", "-ngl", "0", "--cpu-moe"], env=env,
                   stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL, check=True)
    toks = np.fromfile(os.path.join(tmp, "passage", "prompt_tokens.i32"), np.int32).tolist()
    assert len(toks) > max(UBATCH_LENGTHS), len(toks)
    with open(os.path.join(OUT, "ubatch.jsonl"), "w", encoding="utf-8", newline="\n") as f:
        for n in UBATCH_LENGTHS:
            f.write(json.dumps({"id": "ubatch_%d" % n, "tokens": toks[:n]}) + "\n")

    manifest = dict(
        schema=1,
        note="v1 confirmatory corpus. Not used in RC4 or v1 development; frozen before any validation run.",
        prompts=[dict(id=pid, category=cat, sha256_utf8=sha(text.encode("utf-8")))
                 for pid, cat, text in PROMPTS],
        ubatch=[dict(id="ubatch_%d" % n, n_tokens=n,
                     sha256_token_ids=sha(np.asarray(toks[:n], np.int32).tobytes()))
                for n in UBATCH_LENGTHS],
        ubatch_source=dict(generator="tools/v1/make_corpus.py:ubatch_passage", seed=UBATCH_SEED,
                           passage_sha256_utf8=sha(passage.encode("utf-8")), passage_tokens=len(toks)),
        roles=ROLES,
        files={fn: sha(open(os.path.join(OUT, fn), "rb").read()) for fn in ("prompts.jsonl", "ubatch.jsonl")},
    )
    json.dump(manifest, open(os.path.join(OUT, "manifest.json"), "w", encoding="utf-8"), indent=1, ensure_ascii=False)
    print(json.dumps(manifest["files"], indent=1), len(toks), "passage tokens")


if __name__ == "__main__":
    main()
